name: dialog_service
description: A new Flutter package project.
version: 0.1.4
homepage: https://github.com/10urbulut/dialog_service

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=3.3.8"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - icons/


